# For syntax, see https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# This workflow is automatically triggered for every push and pull request, to verify that everything still builds.

name: Build (Manual)
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: { platform: linux, arch: x86_64, os: ubuntu-22.04 }
            target-type: template_debug
          - target: { platform: linux, arch: x86_64, os: ubuntu-22.04 }
            target-type: template_release
          #- target: { platform: macos, arch: universal, os: macos-latest }
          #  target-type: template_debug
          #- target: { platform: macos, arch: universal, os: macos-latest }
          #  target-type: template_release

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Install Meson
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja scons
          sudo apt update
          sudo apt install -y nasm

      # Download SAV1 dependencies
      - name: Download SAV1 dependencies 
        run: |
          cd ./submodules/SAV1/subprojects
          chmod +x download.sh
          ./download.sh

      # Configure Meson
      - name: Meson configure
        run: meson setup ./submodules/SAV1/builddir ./submodules/SAV1

      # Build SAV1
      - name: Meson build
        run: meson compile -C ./submodules/SAV1/builddir

      # Setup godot-cpp dependencies
      - name: Setup godot-cpp
        uses: ./submodules/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      # Build GDExtension (with caches)
      - name: Restore .scons_cache
        uses: ./submodules/godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }}

      - name: Save .scons_cache
        uses: ./submodules/godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
