# For syntax, see https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

name: Build (Manual)
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { platform: windows, arch: x86_64, os: windows-latest },
            { platform: linux, arch: x86_64, os: ubuntu-22.04 },
            { platform: macos, arch: arm64, os: macos-latest }
          ]
        #target-type: [template_debug, template_release]
        target-type: [template_release]
        float-precision: [single]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Install Meson
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja scons

      - name: Install nasm
        if: ${{ matrix.target.platform == 'linux' }}
        run: |
          sudo apt update
          sudo apt install -y nasm

      # Download SAV1 dependencies
      - name: Download SAV1 dependencies
        shell: bash
        run: |
          cd ./submodules/SAV1/subprojects
          chmod +x download.sh
          ./download.sh

      # Configure Meson (Windows)
      - name: Meson configure
        if: ${{ matrix.target.platform == 'windows' }}
        run: meson setup --vsenv -Dc_args="-MT" -Dcpp_args="-MT" ./submodules/SAV1/builddir ./submodules/SAV1

      # Configure Meson (Other)
      - name: Meson configure
        if: ${{ matrix.target.platform != 'windows' }}
        run: meson setup ./submodules/SAV1/builddir ./submodules/SAV1

      # Build SAV1
      - name: Meson build
        run: meson compile -C ./submodules/SAV1/builddir

      # Copy and rename SAV1 libs (Windows)
      - name: Copy and rename SAV1 libs
        if: ${{ matrix.target.platform == 'windows' }}
        shell: bash
        run: |
          cd ./submodules/SAV1/builddir
          cp libsav1.a sav1.lib
          cp ./subprojects/dav1d/src/libdav1d.a ./subprojects/dav1d/src/dav1d.lib
          cp ./subprojects/opus/src/libopus.a ./subprojects/opus/src/opus.lib

      # Setup godot-cpp dependencies
      - name: Setup godot-cpp
        uses: ./submodules/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      # Build GDExtension (with caches)
      - name: Restore .scons_cache
        uses: ./submodules/godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }}

      - name: Save .scons_cache
        uses: ./submodules/godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      # Clean up compilation files
      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item demo/addons/video_toolkit/bin/* -Include *.exp,*.lib,*.pdb -Force

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vtg-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/demo/**

  # Merges all the build artifacts together into a single godot-cpp-template artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: vtg
          pattern: vtg-*
          delete-merged: true
